[package]
name = "ghost-bnet"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ghost-protocol = { path = "../ghost-protocol" }
bytes.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
thiserror.workspace = true
sha1.workspace = true
rand.workspace = true
futures-util = { version = "0.3", default-features = false, features = ["sink"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
