[package]
name = "ghostrs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true


[[bin]]
name = "ghostrs"
path = "src/main.rs"

[dependencies]
ghost-protocol = { path = "../ghost-protocol" }
ghost-net = { path = "../ghost-net" }
ghost-engine = { path = "../ghost-engine" }
ghost-bnet = { path = "../ghost-bnet" }
ghost-spectator = { path = "../ghost-spectator" }
ghost-store = { path = "../ghost-store" }
bytes.workspace = true
rand.workspace = true
tokio.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
